-- Schema -----------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS sdc_ai;

-- Dimension tables -------------------------------------------------------
CREATE TABLE IF NOT EXISTS sdc_ai.qa_source_dim (
    source_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key    TEXT UNIQUE NOT NULL,
    display_name  TEXT,
    owner_team    TEXT,
    active        BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS sdc_ai.qa_model_dim (
    model_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_key      TEXT UNIQUE NOT NULL,
    provider       TEXT NOT NULL,
    version        TEXT,
    context_window INTEGER,
    tags           TEXT[] DEFAULT ARRAY[]::TEXT[],
    active         BOOLEAN NOT NULL DEFAULT TRUE
);

-- Raw payload ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sdc_ai.qa_raw_payload (
    payload_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id        INTEGER REFERENCES sdc_ai.qa_source_dim(source_id),
    source_system    TEXT NOT NULL,
    external_id      TEXT,
    payload_type     TEXT NOT NULL,
    payload_content  TEXT,
    payload_json     JSONB,
    received_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    checksum         TEXT,
    created_by       TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_raw_checksum
    ON sdc_ai.qa_raw_payload (source_system, checksum);

-- Generation runs --------------------------------------------------------
CREATE TABLE IF NOT EXISTS sdc_ai.qa_generation_run (
    run_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_name       TEXT,
    trigger_type   TEXT NOT NULL,
    model_id       INTEGER REFERENCES sdc_ai.qa_model_dim(model_id),
    model_name     TEXT NOT NULL DEFAULT 'unknown-model',
    prompt_tokens  BIGINT,
    completion_tokens BIGINT,
    total_tokens   BIGINT,
    tokens_per_second NUMERIC(12,4),
    overall_qpm    NUMERIC(12,4),
    workflow_duration_seconds NUMERIC(12,4),
    tokens_per_request NUMERIC(12,4),
    started_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at    TIMESTAMPTZ,
    status         TEXT NOT NULL DEFAULT 'running',
    total_items    INTEGER,
    success_count  INTEGER,
    failed_count   INTEGER,
    total_cost_usd NUMERIC(12,4),
    metadata       JSONB
);

CREATE INDEX IF NOT EXISTS idx_run_finished_at
    ON sdc_ai.qa_generation_run (finished_at DESC);

-- QA pairs ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sdc_ai.qa_pair (
    qa_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload_id         BIGINT REFERENCES sdc_ai.qa_raw_payload(payload_id) ON DELETE SET NULL,
    run_id             BIGINT REFERENCES sdc_ai.qa_generation_run(run_id) ON DELETE SET NULL,
    source_id          INTEGER REFERENCES sdc_ai.qa_source_dim(source_id),
    model_id           INTEGER REFERENCES sdc_ai.qa_model_dim(model_id),
    source_key         TEXT,
    source_name        TEXT,
    owner_team         TEXT,
    created_by         TEXT,
    run_name           TEXT,
    trigger_type       TEXT,
    model_key          TEXT,
    model_provider     TEXT,
    model_version      TEXT,
    question           TEXT NOT NULL,
    answer             TEXT NOT NULL,
    answer_format      TEXT DEFAULT 'text',
    model_name         TEXT NOT NULL,
    prompt_tokens      INTEGER,
    completion_tokens  INTEGER,
    latency_ms         INTEGER,
    confidence_score   NUMERIC(6,4),
    eval_score         NUMERIC(6,4),
    status             TEXT NOT NULL DEFAULT 'success',
    error_message      TEXT,
    reviewed_by        TEXT,
    reviewer_comment   TEXT,
    reviewed_at        TIMESTAMPTZ,
    generated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_qa_pair_payload
    ON sdc_ai.qa_pair (payload_id);

CREATE INDEX IF NOT EXISTS idx_qa_pair_source
    ON sdc_ai.qa_pair (source_id);

CREATE INDEX IF NOT EXISTS idx_qa_pair_model
    ON sdc_ai.qa_pair (model_id);

CREATE INDEX IF NOT EXISTS idx_qa_pair_generated_at
    ON sdc_ai.qa_pair (generated_at DESC);

ALTER TABLE sdc_ai.qa_pair
  ADD COLUMN IF NOT EXISTS source_key TEXT,
  ADD COLUMN IF NOT EXISTS source_name TEXT,
  ADD COLUMN IF NOT EXISTS owner_team TEXT,
  ADD COLUMN IF NOT EXISTS created_by TEXT,
  ADD COLUMN IF NOT EXISTS run_name TEXT,
  ADD COLUMN IF NOT EXISTS trigger_type TEXT,
  ADD COLUMN IF NOT EXISTS model_key TEXT,
  ADD COLUMN IF NOT EXISTS model_provider TEXT,
  ADD COLUMN IF NOT EXISTS model_version TEXT;

-- Quality review ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS sdc_ai.qa_quality_review (
    review_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qa_id         BIGINT NOT NULL REFERENCES sdc_ai.qa_pair(qa_id) ON DELETE CASCADE,
    reviewer      TEXT NOT NULL,
    review_type   TEXT NOT NULL,
    score         NUMERIC(6,4),
    label         TEXT,
    comments      TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_quality_review_qa
    ON sdc_ai.qa_quality_review (qa_id);

-- Pipeline events --------------------------------------------------------
CREATE TABLE IF NOT EXISTS sdc_ai.qa_pipeline_event (
    event_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id       BIGINT REFERENCES sdc_ai.qa_generation_run(run_id) ON DELETE SET NULL,
    qa_id        BIGINT REFERENCES sdc_ai.qa_pair(qa_id) ON DELETE CASCADE,
    event_type   TEXT NOT NULL,
    status       TEXT NOT NULL,
    message      TEXT,
    occurred_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata     JSONB
);

CREATE INDEX IF NOT EXISTS idx_pipeline_event_type_time
    ON sdc_ai.qa_pipeline_event (event_type, occurred_at DESC);

-- Monitoring tables ------------------------------------------------------
CREATE TABLE IF NOT EXISTS sdc_ai.qa_metrics_hourly (
    bucket_start          TIMESTAMPTZ PRIMARY KEY,
    bucket_end            TIMESTAMPTZ NOT NULL,
    total_generated       INTEGER NOT NULL,
    success_count         INTEGER NOT NULL,
    failure_count         INTEGER NOT NULL,
    total_prompt_tokens   BIGINT,
    total_completion_tokens BIGINT,
    total_tokens          BIGINT,
    tokens_per_second     NUMERIC(12,4),
    overall_qpm           NUMERIC(12,4),
    total_duration_seconds NUMERIC(12,4),
    tokens_per_request    NUMERIC(12,4),
    avg_latency_ms        NUMERIC(10,2),
    p95_latency_ms        NUMERIC(10,2),
    avg_prompt_tokens     NUMERIC(10,2),
    avg_completion_tokens NUMERIC(10,2),
    avg_confidence        NUMERIC(6,4),
    source_breakdown      JSONB,
    model_breakdown       JSONB
);

CREATE TABLE IF NOT EXISTS sdc_ai.qa_metrics_daily (
    date_key          DATE PRIMARY KEY,
    total_generated   INTEGER NOT NULL,
    success_count     INTEGER NOT NULL,
    failure_count     INTEGER NOT NULL,
    total_prompt_tokens BIGINT,
    total_completion_tokens BIGINT,
    total_tokens      BIGINT,
    tokens_per_second NUMERIC(12,4),
    overall_qpm       NUMERIC(12,4),
    total_duration_seconds NUMERIC(12,4),
    tokens_per_request NUMERIC(12,4),
    avg_latency_ms    NUMERIC(10,2),
    p95_latency_ms    NUMERIC(10,2),
    avg_eval_score    NUMERIC(6,4),
    avg_confidence    NUMERIC(6,4),
    source_breakdown  JSONB,
    model_breakdown   JSONB
);

-- Materialized view ------------------------------------------------------
CREATE MATERIALIZED VIEW IF NOT EXISTS sdc_ai.qa_metrics_hourly_model_source AS
SELECT
    date_trunc('hour', qp.generated_at) AS bucket_start,
    qp.model_id,
    qp.source_id,
    COUNT(*) FILTER (WHERE qp.status = 'success') AS success_count,
    COUNT(*) FILTER (WHERE qp.status <> 'success') AS failure_count,
    AVG(qp.latency_ms) AS avg_latency_ms,
    percentile_cont(0.95) WITHIN GROUP (ORDER BY qp.latency_ms) AS p95_latency_ms,
    AVG(qp.eval_score) AS avg_eval_score,
    AVG(qp.confidence_score) AS avg_confidence
FROM sdc_ai.qa_pair qp
GROUP BY 1,2,3
WITH NO DATA;

CREATE INDEX IF NOT EXISTS idx_metrics_hourly_model_source
    ON sdc_ai.qa_metrics_hourly_model_source (bucket_start DESC, model_id, source_id);

-- Optional: refresh when data is available
-- REFRESH MATERIALIZED VIEW CONCURRENTLY sdc_ai.qa_metrics_hourly_model_source;
ALTER TABLE sdc_ai.qa_generation_run
  ADD COLUMN prompt_tokens BIGINT,
  ADD COLUMN completion_tokens BIGINT,
  ADD COLUMN total_tokens BIGINT,
  ADD COLUMN tokens_per_second NUMERIC(12,4),
  ADD COLUMN overall_qpm NUMERIC(12,4),
  ADD COLUMN workflow_duration_seconds NUMERIC(12,4),
  ADD COLUMN tokens_per_request NUMERIC(12,4);

ALTER TABLE sdc_ai.qa_metrics_hourly
  ADD COLUMN total_prompt_tokens BIGINT,
  ADD COLUMN total_completion_tokens BIGINT,
  ADD COLUMN total_tokens BIGINT,
  ADD COLUMN tokens_per_second NUMERIC(12,4),
  ADD COLUMN overall_qpm NUMERIC(12,4),
  ADD COLUMN total_duration_seconds NUMERIC(12,4),
  ADD COLUMN tokens_per_request NUMERIC(12,4);

ALTER TABLE sdc_ai.qa_metrics_daily
  ADD COLUMN total_prompt_tokens BIGINT,
  ADD COLUMN total_completion_tokens BIGINT,
  ADD COLUMN total_tokens BIGINT,
  ADD COLUMN tokens_per_second NUMERIC(12,4),
  ADD COLUMN overall_qpm NUMERIC(12,4),
  ADD COLUMN total_duration_seconds NUMERIC(12,4),
  ADD COLUMN tokens_per_request NUMERIC(12,4);
